import { useState } from 'react';
import { api } from '../lib/api';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from './ui/dialog';

const blankVenue = () => ({ key: crypto.randomUUID(), name: '', addressLine1: '', addressLine2: '', city: '', region: '', postalCode: '', countryCode: 'US', timezone: Intl.DateTimeFormat().resolvedOptions().timeZone, privacy: 'public' });
export default function OnboardingForm({ onClose, onSaved }) {
  const [step, setStep] = useState(0); const [recipient, setRecipient] = useState({ displayName: '', email: '', phone: '', role: 'owner', financeAuthorized: false });
  const [organization, setOrganization] = useState({ name: '', description: '', planTier: 'free', website: '' });
  const [venues, setVenues] = useState([]); const [authority, setAuthority] = useState(false); const [reason, setReason] = useState('');
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [result, setResult] = useState(null);
  async function submit(event) {
    event.preventDefault(); setError('');
    if (step < 2) { setStep(step + 1); return; }
    setBusy(true);
    try { setResult(await api('/admin/onboarding', { method: 'POST', body: JSON.stringify({ kind: 'organization', recipient: { ...recipient, financeAuthorized: recipient.role === 'manager' && recipient.financeAuthorized }, organization: { ...organization, website: organization.website || undefined }, venues: venues.map(({ key, ...venue }) => venue), confirmedAuthority: authority, reason }) })); }
    catch (err) { setError(err.message); } finally { setBusy(false); }
  }
  const person = (key) => (event) => setRecipient((prior) => ({ ...prior, [key]: event.target.value }));
  const business = (key) => (event) => setOrganization((prior) => ({ ...prior, [key]: event.target.value }));
  return <Dialog open onOpenChange={(open) => !open && !busy && onClose()}><DialogContent className="dialog management-dialog"><DialogHeader><DialogTitle>Onboard business</DialogTitle><DialogDescription>Whether this is for an event creator, venue, or organization, the initial contact must verify their email to receive access.</DialogDescription></DialogHeader>{result ? <div className="success"><b>Onboarding prepared.</b><p>{result.delivery === 'queued' ? 'Setup email is queued. Delivery is not yet confirmed.' : 'Email delivery is unavailable. The pending workspace is saved; resend from Account invitations when delivery is configured.'}</p><p>{recipient.role === 'manager' ? 'The initial contact will be a manager. Ownership has not been granted.' : 'The recipient will become an owner after accepting the invitation.'}</p><p>No password or setup link is exposed to administrators.</p><Button onClick={() => onSaved(result)}>Done</Button></div> : <><ol className="management-stepper" aria-label="Onboarding progress">{['Initial contact', 'Business & optional venues', 'Review & invite'].map((title, index) => <li key={title} aria-current={step === index ? 'step' : undefined}>{index + 1}. {title}</li>)}</ol><form onSubmit={submit}>
    {step === 0 && <section aria-label="Initial contact"><h3>Initial contact</h3><div className="management-form">{[['displayName', 'Full name', 'text'], ['email', 'Email', 'email'], ['phone', 'Phone', 'tel']].map(([key, title, type]) => <label htmlFor={`onboarding-${key}`} key={key}>{title}<Input id={`onboarding-${key}`} name={key} type={type} required maxLength={key === 'email' ? 320 : key === 'phone' ? 32 : 120} value={recipient[key]} onChange={person(key)}/></label>)}<label htmlFor="onboarding-role">Initial business role<select id="onboarding-role" value={recipient.role} onChange={(event) => setRecipient((prior) => ({ ...prior, role: event.target.value, financeAuthorized: false }))}><option value="owner">Owner</option><option value="manager">Manager</option></select></label></div>{recipient.role === 'manager' && <><p className="notice">A manager can be the business’s first contact. Add an owner later through the ownership controls.</p><label className="management-confirm" htmlFor="onboarding-finance"><input id="onboarding-finance" type="checkbox" checked={recipient.financeAuthorized} onChange={(event) => setRecipient((prior) => ({ ...prior, financeAuthorized: event.target.checked }))}/>Grant separate finance permission</label><small>Operational management alone does not grant finance access. Payment account setup remains a future phase.</small></>}<p className="notice">The email is verified during acceptance. The recipient chooses their own password or accepts with an existing account.</p></section>}
    {step === 1 && <section aria-label="Business and venues"><h3>Business workspace</h3><div className="management-form"><label htmlFor="onboarding-business-name">Business name<Input id="onboarding-business-name" required maxLength={160} value={organization.name} onChange={business('name')}/></label><label htmlFor="onboarding-description">Description (optional)<Input id="onboarding-description" value={organization.description} onChange={business('description')}/></label><label htmlFor="onboarding-website">Website (optional)<Input id="onboarding-website" type="url" value={organization.website} onChange={business('website')}/></label><label htmlFor="onboarding-plan">Plan<select id="onboarding-plan" value={organization.planTier} onChange={business('planTier')}><option value="free">Free</option><option value="premium">Premium</option></select></label></div><h3>Saved venues (optional)</h3><p className="notice">A business can have no saved venue or business address. Event locations can be supplied when creating events.</p>{venues.map((venue, index) => <fieldset key={venue.key}><legend>Venue {index + 1}</legend><div className="management-form">{[['name', 'Venue name'], ['addressLine1', 'Street address'], ['addressLine2', 'Address line 2 (optional)'], ['city', 'City'], ['region', 'State / region'], ['postalCode', 'Postal code'], ['countryCode', 'Country code']].map(([key, title]) => <label htmlFor={`onboarding-venue-${index}-${key}`} key={key}>{title}<Input id={`onboarding-venue-${index}-${key}`} required={['name', 'addressLine1', 'city', 'countryCode'].includes(key)} value={venue[key]} onChange={(event) => setVenues((prior) => prior.map((item) => item.key === venue.key ? { ...item, [key]: event.target.value } : item))}/></label>)}</div><Button type="button" variant="outline" onClick={() => setVenues((prior) => prior.filter((item) => item.key !== venue.key))}>Remove venue from this draft</Button></fieldset>)}<Button type="button" variant="outline" disabled={venues.length >= 25} onClick={() => setVenues((prior) => [...prior, blankVenue()])}>Add venue</Button></section>}
    {step === 2 && <section aria-label="Review and invite"><h3>Review invitation</h3><dl className="management-review"><div><dt>Business</dt><dd>{organization.name} · {organization.planTier} plan</dd></div><div><dt>Initial contact</dt><dd>{recipient.displayName} · {recipient.email} · {recipient.phone}</dd></div><div><dt>Access after acceptance</dt><dd>{recipient.role === 'owner' ? 'Owner' : recipient.financeAuthorized ? 'Manager with finance permission' : 'Manager without finance permission'}</dd></div><div><dt>Saved venues</dt><dd>{venues.length ? venues.map((venue) => <span className="management-review-venue" key={venue.key}>{venue.name} · {venue.addressLine1}, {venue.city}</span>) : 'No saved venues'}</dd></div></dl><label className="management-confirm" htmlFor="onboarding-authority"><input id="onboarding-authority" type="checkbox" required checked={authority} onChange={(event) => setAuthority(event.target.checked)}/>I have confirmed the contact’s authority to represent this business.</label><label className="management-reason" htmlFor="onboarding-reason">Required audit reason<textarea id="onboarding-reason" minLength={3} maxLength={500} required value={reason} onChange={(event) => setReason(event.target.value)}/></label><p className="notice">Admin-created businesses have already been reviewed. Account activation and business approval remain separate from future payment readiness.</p></section>}
    {error && <p className="error" role="alert">{error}</p>}<div className="management-dialog-actions">{step > 0 && <Button type="button" variant="outline" disabled={busy} onClick={() => { setStep(step - 1); setError(''); }}>Back</Button>}<Button type="button" variant="outline" disabled={busy} onClick={onClose}>Cancel</Button><Button type="submit" disabled={busy}>{busy ? 'Preparing…' : step === 2 ? 'Prepare and invite recipient' : 'Continue'}</Button></div>
  </form></>}</DialogContent></Dialog>;
}
