import { useState } from 'react';
import { useAdminResource } from '../hooks/useAdminResource';
import { formatDate, formatMoney } from '../lib/admin';
import { Button } from './ui/button';
import { Card } from './ui/card';
import { ResourceState, Pager } from './ResourceState';
import { hasAdminPermission } from '../lib/permissions';
import { readSession } from '../lib/api';
import PageHeader from './PageHeader';

export default function Overview({ onOpenRecord, onNavigate }) {
  const [days, setDays] = useState('30'); const [page, setPage] = useState(1); const [refresh, setRefresh] = useState(0);
  const canReport = hasAdminPermission(readSession()?.user, 'reports.view');
  const report = useAdminResource(canReport ? `/admin/reports/summary?days=${days}&timezone=${encodeURIComponent(Intl.DateTimeFormat().resolvedOptions().timeZone)}` : null, refresh);
  const attention = useAdminResource(`/admin/overview/needs-attention?page=${page}&pageSize=10`, refresh);
  const summary = report.data?.summary;
  const financial = report.data?.financial;
  const metrics = [['Face-value sales', financial?.faceValueSalesCents ?? summary?.salesCents, 'Recorded paid order subtotals'], ['Customer paid', financial?.customerPaidCents, 'Recorded purchase totals'], ['Combined fees recorded', financial?.combinedFeesCents, 'Buyer-paid and business-absorbed fees'], ['Business-absorbed fees', financial?.businessAbsorbedFeesCents, 'Deducted from business proceeds'], ['Business proceeds before provider', financial?.businessProceedsBeforeProviderCents, 'Face value less absorbed fees and commissions'], ['Platform contribution estimate', financial?.modeledContributionCents, 'Historical pricing model; provider settlement unverified'], ['Paid purchases', summary?.orders, 'Distinct paid orders', false], ['Units sold', summary?.units, 'Tickets, packages and reservations', false]];
  return <div className="management"><PageHeader title="Overview" description="Platform performance and the issues that need your attention."><Button variant="outline" onClick={() => setRefresh((value) => value + 1)}>Refresh</Button></PageHeader><div className="management-toolbar"><label>Performance period<select aria-label="Overview period" value={days} onChange={(event) => setDays(event.target.value)}>{['7', '30', '90', '365'].map((value) => <option key={value} value={value}>Last {value} days</option>)}</select></label>{canReport && <Button onClick={() => onNavigate(`?section=analytics&period=${days}`)}>Explore analytics</Button>}</div><ResourceState loading={report.loading} error={report.error} onRetry={() => setRefresh((value) => value + 1)}>{summary && <div className="metrics">{metrics.map(([title, value, note, money = true]) => <Card className="stat" key={title}><span>{title}</span><strong>{value == null ? 'Unavailable' : money ? formatMoney(value) : value.toLocaleString()}</strong><small>{note}</small></Card>)}</div>}</ResourceState><section className="panel management-panel"><div className="record-heading"><div><p className="eyebrow">PLATFORM OPERATIONS</p><h2>Needs attention</h2><p>Support cases, pending account setup and platform failures.</p></div><Button variant="outline" onClick={() => onNavigate('?section=support')}>Open support</Button></div><ResourceState loading={attention.loading} error={attention.error} onRetry={() => setRefresh((value) => value + 1)}>{attention.data && <>{attention.data.items.length ? <div className="management-records">{attention.data.items.map((item) => <article className="management-record" key={item.id}><div><h3>{item.title}</h3><p className="management-record-state">{item.priority} · {item.kind.replaceAll('_', ' ')}</p><small>{formatDate(item.createdAt, true)}</small></div><Button variant="outline" onClick={() => item.recordType === 'support_case' ? onNavigate(`?section=support&case=${item.recordId}`) : item.recordType === 'onboarding_invitation' ? onOpenRecord('onboarding_invitations', item.recordId) : item.recordType === 'email_outbox' ? onOpenRecord('email_outbox', item.recordId) : onNavigate('?section=support&supportView=alerts')}>Review</Button></article>)}</div> : <div className="empty">No issues need attention.</div>}<Pager result={attention.data} onPage={setPage}/></>}</ResourceState></section>{report.data?.daily?.length > 0 && <section className="panel management-panel"><h2>Sales pace</h2><div className="sales-pace">{report.data.daily.slice(-14).map((item) => <div key={item.date}><span>{item.date.slice(5)}</span><strong>{formatMoney(item.salesCents)}</strong><small>{item.orders} purchases</small></div>)}</div></section>}</div>;
}
