const { z } = require('zod');
const uuid = z.string().uuid();
const date = z.coerce.date();
const organization = z.object({ name: z.string().min(2).max(160), slug: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/), description: z.string().max(5000).optional(), planTier: z.enum(['free', 'gold']).default('free') });
const event = z.object({ organizationId: uuid.nullish(), locationId: uuid.nullish(), title: z.string().min(2).max(180), slug: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/), summary: z.string().max(500).optional(), description: z.string().max(20_000).optional(), category: z.string().max(80).default('other'), startsAt: date, endsAt: date, capacity: z.number().int().nonnegative().nullish(), guestlistCapacity: z.number().int().nonnegative().default(0), status: z.enum(['draft', 'published']).default('draft') }).refine((data) => data.endsAt > data.startsAt, { message: 'endsAt must be after startsAt', path: ['endsAt'] });
const offering = z.object({ name: z.string().min(1).max(160), description: z.string().max(5000).optional(), kind: z.enum(['ticket', 'package', 'reservation']).default('ticket'), priceCents: z.number().int().nonnegative(), currency: z.string().length(3).default('USD'), inventoryMode: z.enum(['finite', 'unlimited']).default('finite'), quantityTotal: z.number().int().nonnegative().nullish(), entriesPerUnit: z.number().int().positive().default(1), minPerOrder: z.number().int().positive().default(1), maxPerOrder: z.number().int().positive().default(10), salesStartAt: date.optional(), salesEndAt: date.optional(), visibility: z.enum(['public', 'hidden', 'password']).default('public') }).refine((data) => data.inventoryMode === 'unlimited' || data.quantityTotal != null, { message: 'quantityTotal is required for finite inventory' });
const orgAffiliate = z.object({ userId: uuid, code: z.string().min(3).max(48), defaultCommissionBps: z.number().int().min(0).max(10_000).default(0), defaultGuestlistAllocation: z.number().int().nonnegative().default(0) });
const eventAffiliate = z.object({ userId: uuid, orgAffiliateId: uuid.nullish(), code: z.string().min(3).max(48), commissionBps: z.number().int().min(0).max(10_000).nullish(), guestlistAllocation: z.number().int().nonnegative().nullish() });
const checkout = z.object({ eventId: uuid, idempotencyKey: z.string().min(8).max(100), affiliateCode: z.string().max(48).optional(), items: z.array(z.object({ offeringId: uuid, quantity: z.number().int().positive() })).min(1), payment: z.object({ provider: z.string().max(40), reference: z.string().min(1).max(160), status: z.literal('succeeded') }).optional() });
const guestlist = z.object({ partySize: z.number().int().positive().max(20).default(1), affiliateCode: z.string().max(48).optional() });
const checkIn = z.object({ eventId: uuid, qrToken: z.string().min(20) });
module.exports = { organization, event, offering, orgAffiliate, eventAffiliate, checkout, guestlist, checkIn };

