const express = require('express');
const { asyncHandler, validate } = require('../http/middleware');
const schemas = require('../http/schemas');
const businessSchemas = require('../http/business-schemas');
const { createBusinessService } = require('../services/business-service');
const { createAdminService } = require('../services/admin-service');
const adminSchemas = require('../http/admin-schemas');
const { analyticsQuery } = require('../http/analytics-schemas');
const { createAnalyticsService } = require('../services/analytics-service');
const { createTeamService } = require('../services/team-service');
const { createEventWorkspaceService } = require('../services/event-workspace-service');
const { createReferralLinkService } = require('../services/referral-link-service');
const { z } = require('zod');
const { optionalPhone } = require('../domain/phone');
const { createCustomerAccountService } = require('../services/customer-account-service');

function createRouter({ publicController, managementController, commerceController, authController, requireUser, models, permissions, invitations, notifications, tokenSecret }) {
  const router = express.Router();
  const business = createBusinessService({ models, permissions });
  const admin = createAdminService({ models, permissions });
  const analytics = createAnalyticsService({ models, permissions });
  const team = createTeamService({ models, permissions });
  const eventWorkspace = createEventWorkspaceService({ models, permissions });
  const referralLinks = createReferralLinkService({ models });
  const account = createCustomerAccountService({ models, tokenSecret });
  router.use('/customer', requireUser, (req, res, next) => { res.set('Cache-Control', 'no-store'); next(); });
  router.get('/customer/bookings', asyncHandler(async (req, res) => res.json({ data: await account.bookings(req.userId, z.object({ page: z.coerce.number().int().min(1).max(10000).default(1), period: z.enum(['upcoming', 'past']).default('upcoming') }).parse(req.query)) })));
  router.get('/customer/tickets/:id', asyncHandler(async (req, res) => res.json({ data: await account.ticket(req.userId, z.string().uuid().parse(req.params.id)) })));
  router.get('/customer/purchases/:id/tickets', asyncHandler(async (req, res) => res.json({ data: await account.purchaseTickets(req.userId, z.string().uuid().parse(req.params.id)) })));
  router.get('/customer/guestlists/:id/pass', asyncHandler(async (req, res) => res.json({ data: await account.guestlistPass(req.userId, z.string().uuid().parse(req.params.id)) })));
  router.get('/customer/connections', asyncHandler(async (req, res) => res.json({ data: await account.connections(req.userId) })));
  router.patch('/customer/profile', validate(z.object({ displayName: z.string().trim().min(1).max(120), phone: optionalPhone, marketingConsent: z.boolean(), transactionalSmsConsent: z.boolean(), marketingSmsConsent: z.boolean() }).strict()), asyncHandler(async (req, res) => res.json({ data: await account.updateProfile(req.userId, req.body) })));
  const eventPerson = z.object({ userId: z.string().uuid().optional(), email: z.string().trim().email().optional(), commissionBps: z.number().int().min(0).max(4000), status: z.enum(['active', 'inactive']).default('active') }).refine((v) => Boolean(v.userId) !== Boolean(v.email), 'Provide a user or an email');
  router.get('/business/events/:eventId/detail', requireUser, asyncHandler(async (req, res) => res.json({ data: await eventWorkspace.detail(req.userId, req.params.eventId) })));
  router.get('/business/events/:eventId/referral-link', requireUser, asyncHandler(async (req, res) => res.json({ data: await referralLinks.ownLink(req.userId, req.params.eventId) })));
  router.post('/events/:eventId/referral-visits', validate(z.object({ code: z.string().min(3).max(48), sessionKey: z.string().uuid().optional() })), asyncHandler(async (req, res) => res.json({ data: await referralLinks.visit(req.params.eventId, req.body.code, req.body.sessionKey) })));
  router.put('/business/events/:eventId/people', requireUser, validate(eventPerson), asyncHandler(async (req, res) => res.json({ data: await eventWorkspace.savePerson(req.userId, req.params.eventId, req.body) })));
  const inviteInput = z.object({ email: z.string().trim().email().max(320), phone: optionalPhone, role: z.enum(['manager', 'employee', 'affiliate']) });
  router.get('/business/events/:eventId/invitations',requireUser,asyncHandler(async (req,res) => res.json({data:await team.eventInvitations(req.userId,req.params.eventId)})));
  router.post('/business/events/:eventId/invitations',requireUser,validate(inviteInput.pick({email:true,phone:true}).extend({commissionBps:z.number().int().min(0).max(4000).default(0)})),asyncHandler(async (req,res) => res.status(201).json({data:await team.inviteEvent(req.userId,req.params.eventId,req.body)})));
  router.delete('/business/events/:eventId/invitations/:invitationId',requireUser,asyncHandler(async (req,res) => res.json({data:await team.revokeEvent(req.userId,req.params.eventId,req.params.invitationId)})));
  router.get('/business/organizations/:organizationId/team', requireUser, asyncHandler(async (req, res) => res.json({ data: await team.roster(req.userId, req.params.organizationId) })));
  router.post('/business/organizations/:organizationId/invitations', requireUser, validate(inviteInput), asyncHandler(async (req, res) => res.status(201).json({ data: await team.invite(req.userId, req.params.organizationId, req.body) })));
  router.delete('/business/organizations/:organizationId/invitations/:invitationId', requireUser, asyncHandler(async (req, res) => res.json({ data: await team.revoke(req.userId, req.params.organizationId, req.params.invitationId) })));
  router.post('/business/organizations/:organizationId/invitations/:invitationId/resend', requireUser, asyncHandler(async (req, res) => res.json({ data: await team.resend(req.userId, req.params.organizationId, req.params.invitationId) })));
  router.get('/team/invitations/:token', asyncHandler(async (req, res) => res.json({ data: await team.invitation(req.params.token) })));
  router.post('/team/invitations/:token/accept', requireUser, asyncHandler(async (req, res) => res.json({ data: await team.accept(req.userId, req.params.token) })));
  router.get('/admin/analytics', requireUser, asyncHandler(async (req, res) => res.json({ data: await analytics.adminReport(req.userId, analyticsQuery.parse(req.query)) })));
  router.get('/business/analytics', requireUser, asyncHandler(async (req, res) => res.json({ data: await analytics.businessReport(req.userId, analyticsQuery.parse(req.query)) })));
  router.get('/admin/workspace', requireUser, asyncHandler(async (req, res) => res.json({ data: await admin.workspace(req.userId, adminSchemas.reportQuery.parse(req.query)) })));
  router.patch('/admin/users/:id', requireUser, validate(adminSchemas.userUpdate), asyncHandler(async (req, res) => res.json({ data: await admin.updateUser(req.userId, req.params.id, req.body) })));
  router.patch('/admin/organizations/:id', requireUser, validate(adminSchemas.organizationUpdate), asyncHandler(async (req, res) => res.json({ data: await admin.updateOrganization(req.userId, req.params.id, req.body) })));
  router.patch('/admin/events/:id', requireUser, validate(adminSchemas.eventUpdate), asyncHandler(async (req, res) => res.json({ data: await admin.updateEvent(req.userId, req.params.id, req.body) })));
  router.post('/admin/demo-users', requireUser, validate(adminSchemas.demoUser), asyncHandler(async (req, res) => res.status(201).json({ data: await admin.createDemoUser(req.userId, req.body) })));
  router.get('/business/workspace', requireUser, asyncHandler(async (req, res) => res.json({ data: await business.workspace(req.userId, businessSchemas.reportQuery.parse(req.query)) })));
  router.post('/business/events', requireUser, validate(businessSchemas.eventEditor), asyncHandler(async (req, res) => res.status(201).json({ data: await business.saveEvent(req.userId, null, req.body) })));
  router.put('/business/events/:eventId', requireUser, validate(businessSchemas.eventEditor), asyncHandler(async (req, res) => res.json({ data: await business.saveEvent(req.userId, req.params.eventId, req.body) })));
  router.post('/auth/register', validate(schemas.register), asyncHandler(authController.register));
  router.post('/auth/sign-in', validate(schemas.signIn), asyncHandler(authController.signIn));
  router.get('/auth/me', requireUser, asyncHandler(authController.me));
  router.get('/events', asyncHandler(publicController.listEvents));
  router.get('/events/:eventId', asyncHandler(publicController.getEvent));
  router.post('/organizations', requireUser, validate(schemas.organization), asyncHandler(managementController.createOrganization));
  router.post('/organizations/:organizationId/affiliates', requireUser, validate(schemas.orgAffiliate), asyncHandler(managementController.addOrgAffiliate));
  router.post('/events', requireUser, validate(schemas.event), asyncHandler(managementController.createEvent));
  router.post('/events/:eventId/offerings', requireUser, validate(schemas.offering), asyncHandler(managementController.addOffering));
  router.post('/events/:eventId/affiliates', requireUser, validate(schemas.eventAffiliate), asyncHandler(managementController.addEventAffiliate));
  router.patch('/business/events/:eventId/guestlist-capacity', requireUser, validate(schemas.guestlistCapacity), asyncHandler(managementController.updateGuestlistCapacity));
  router.patch('/business/events/:eventId/affiliates/:eventAffiliateId/guestlist-allocation', requireUser, validate(schemas.affiliateGuestlistAllocation), asyncHandler(managementController.updateAffiliateGuestlistAllocation));
  router.get('/business/events/:eventId/guestlist-settings', requireUser, asyncHandler(managementController.guestlistSettings));
  router.get('/business/events/:eventId/guestlist-invite-pools', requireUser, asyncHandler(async (req, res) => res.json({ data: await invitations.pools(req.userId, req.params.eventId) })));
  router.post('/business/events/:eventId/guestlist-invitations', requireUser, validate(schemas.guestlistInvite), asyncHandler(async (req, res) => res.status(201).json({ data: await invitations.invite(req.userId, req.params.eventId, req.body) })));
  router.post('/guestlist-invitations/:token/claim', requireUser, asyncHandler(async (req, res) => res.json({ data: await invitations.claim(req.params.token, req.userId) })));
  router.get('/notifications', requireUser, asyncHandler(async (req, res) => res.json({ data: { items: await notifications.list(req.userId), unreadCount: await notifications.unreadCount(req.userId) } })));
  router.post('/notifications/:id/read', requireUser, asyncHandler(async (req, res) => res.json({ data: await notifications.markRead(req.userId, req.params.id) })));
  router.post('/events/:eventId/guestlist', requireUser, validate(schemas.guestlist), asyncHandler(commerceController.requestGuestlist));
  router.get('/business/events/:eventId/guestlist', requireUser, asyncHandler(commerceController.listGuestlistRequests));
  router.post('/business/events/:eventId/guestlist/:entryId/decision', requireUser, validate(schemas.guestlistDecision), asyncHandler(commerceController.reviewGuestlist));
  router.post('/orders', requireUser, validate(schemas.checkout), asyncHandler(commerceController.checkout));
  router.get('/orders/:orderId', requireUser, asyncHandler(commerceController.getOrder));
  router.post('/check-ins', requireUser, validate(schemas.checkIn), asyncHandler(commerceController.checkIn));
  router.get('/business/events/:eventId/analytics', requireUser, asyncHandler(managementController.eventAnalytics));
  router.get('/admin/overview', requireUser, asyncHandler(managementController.adminOverview));
  return router;
}
module.exports = { createRouter };
