const express = require('express');
const { createBusinessService } = require('../services/business-service');
const { createAdminService } = require('../services/admin-service');
const { createAnalyticsService } = require('../services/analytics-service');
const { createTeamService } = require('../services/team-service');
const { createEventWorkspaceService } = require('../services/event-workspace-service');
const { createReferralLinkService } = require('../services/referral-link-service');
const { createCustomerAccountService } = require('../services/customer-account-service');
const { createCustomerSavedService } = require('../services/customer-saved-service');
const { createAdmissionsService } = require('../services/admissions-service');
const { createBusinessReadService } = require('../services/business-read-service');
const { createBusinessEventReadService } = require('../services/business-event-read-service');
const { createBusinessInstructionsReadService } = require('../services/business-instructions-read-service');
const { createBusinessReportService } = require('../services/business-report-service');
const { createReportExportService } = require('../services/report-export-service');
const { createAdminReportService } = require('../services/admin-report-service');
const { createBusinessTeamReadService } = require('../services/business-team-read-service');
const { createBusinessEventReuseService } = require('../services/business-event-reuse-service');

function createRouter(options) {
  const { publicController, managementController, commerceController, authController, auth, requireUser, models, permissions, invitations, notifications, email, customerAppUrl = 'http://localhost:5173', businessAppUrl = 'http://localhost:5174/app', qrTokenSecret, deliveryTrackingConfigured = false } = options;
  const router = require('./contract-router').instrumentRouter(express.Router(), { requireUser, permissions });
  const business = createBusinessService({ models, permissions, email, customerAppUrl, businessAppUrl });
  const businessRead = createBusinessReadService({ models, email, deliveryTrackingConfigured });
  const businessReports = createBusinessReportService({ models, businessRead });
  const adminReports = createAdminReportService({ models, permissions, businessRead, reports: businessReports });
  const reportExports = createReportExportService({ models, businessRead, reports: businessReports, historicalReports: adminReports.reports });
  router.reportExports = reportExports;
  const businessTeamRead = createBusinessTeamReadService({ models, permissions });
  const businessEventReuse = createBusinessEventReuseService({ models, permissions });
  const businessEventRead = createBusinessEventReadService({ models });
  const businessInstructionsRead = createBusinessInstructionsReadService({ models, permissions, email, deliveryTrackingConfigured });
  const admin = createAdminService({ models, permissions, email, customerAppUrl });
  const adminSupport = require('../services/admin-support-service').createAdminSupportService({ models, permissions });
  const analytics = createAnalyticsService({ models, permissions });
  const team = createTeamService({ models, permissions, email, businessAppUrl });
  const eventWorkspace = createEventWorkspaceService({ models, permissions, email, businessAppUrl });
  const referralLinks = createReferralLinkService({ models });
  const account = createCustomerAccountService({ models, tokenSecret: qrTokenSecret });
  const saved = createCustomerSavedService({ models });
  const admissions = createAdmissionsService({ models, permissions });
  const context = { router, publicController, managementController, commerceController, authController, auth, requireUser, models, permissions, invitations, notifications, email, customerAppUrl, businessAppUrl, qrTokenSecret, deliveryTrackingConfigured, business, businessRead, businessReports, adminReports, reportExports, businessTeamRead, businessEventReuse, businessEventRead, businessInstructionsRead, admin, adminSupport, analytics, team, eventWorkspace, referralLinks, account, saved, admissions };
  require('./public').registerPublicRoutes(context);
  require('./account').registerAccountRoutes(context);
  require('./customer').registerCustomerRoutes(context);
  require('./admissions').registerAdmissionsRoutes(context);
  require('./reporting').registerReportingRoutes(context);
  require('./business').registerBusinessRoutes(context);
  require('./admin').registerAdminRoutes(context);
  require('./admin-events').registerAdminEventRoutes(context);
  require('./admin-support').registerAdminSupportRoutes(context);
  require('./business-venues').registerVenueRoutes({ ...context, asyncHandler: require('./contract-router').asyncHandler });
  let openApi;
  router.get('/openapi.json', (_req, res) => {
    openApi ||= require('../http/api-contract').generateOpenApi(router.contracts);
    res.json(openApi);
  });
  return router;
}
module.exports = { createRouter };
