const test=require('node:test');
const assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
const {assertManagedTestDatabase}=require('../scripts/test-database.cjs');
const {createBusinessPaymentAccountService,RESPONSIBILITIES,resolvePaymentAccount}=require('../src/services/business-payment-account-service');
const deferred=()=>{let resolve;const promise=new Promise(done=>resolve=done);return {promise,resolve};};
test('sandbox profiles persist scoped provider readiness and lock event merchant after payment history',{timeout:30000},async()=>{
  assertManagedTestDatabase();
  const db=require('../src/db/sequelize').createSequelize(require('../src/config').getConfig());
  const m=require('../src/db/models').initModels(db);
  let providerCalls=0;const remote={id:`acct_${randomUUID().replaceAll('-','')}`,object:'v2.core.account',livemode:false,applied_configurations:['merchant'],dashboard:'full',defaults:{responsibilities:{...RESPONSIBILITIES,requirements_collector:'stripe'}},configuration:{merchant:{applied:true,capabilities:{card_payments:{status:'active'},stripe_balance:{payouts:{status:'active'}}}}},requirements:{entries:[]}};
  const stripe={mode:'test',enabled:true,createAccount:async()=>{providerCalls++;return remote;},retrieveAccount:async()=>remote,createAccountLink:async()=>({object:'v2.core.account_link',account:remote.id,livemode:false,url:'https://connect.stripe.test/mock-only',expires_at:'2033-05-18T03:33:20.000Z'})};
  try {
    const owner=await m.User.create({displayName:'Sandbox Owner',email:`owner-${randomUUID()}@example.test`});
    const other=await m.User.create({displayName:'Unrelated Owner',email:`other-${randomUUID()}@example.test`});
    const org=await m.Organization.create({name:'Sandbox nightclub',slug:`sandbox-${randomUUID()}`,onboardingEstablished:true});
    const org2=await m.Organization.create({name:'Other business',slug:`other-${randomUUID()}`,onboardingEstablished:true});
    await m.OrganizationOwner.create({organizationId:org.id,userId:owner.id,role:'owner'});
    await m.OrganizationOwner.create({organizationId:org2.id,userId:other.id,role:'owner'});
    const service=createBusinessPaymentAccountService({models:m,stripe,businessAppUrl:'https://business.example/app'});
    const input={name:'Club A merchant',idempotencyKey:randomUUID()};const profile=await service.create(owner.id,org.id,input);
    await service.create(owner.id,org.id,input);assert.equal(providerCalls,1);
    await assert.rejects(service.list(other.id,org.id),{code:'FORBIDDEN'});
    await assert.rejects(service.onboarding(other.id,org2.id,profile.id),{code:'NOT_FOUND'});
    const before=await m.PaymentAccount.findByPk(profile.id);assert.equal(before.chargesEnabled,false);
    await service.onboarding(owner.id,org.id,profile.id);await before.reload();assert.equal(before.chargesEnabled,false);
    const synchronized=await service.synchronize(owner.id,org.id,profile.id);assert.equal(synchronized.paymentsReady,true);
    await service.selectDefault(owner.id,org.id,profile.id);
    const event=await m.Event.create({creatorUserId:owner.id,organizationId:org.id,title:'Sandbox Event',slug:`event-${randomUUID()}`,startsAt:new Date(Date.now()+3600000),endsAt:new Date(Date.now()+7200000)});
    assert.equal((await resolvePaymentAccount({models:m,event,refresh:false})).id,profile.id);
    await service.selectEvent(owner.id,event.id,profile.id);
    await m.Order.create({buyerUserId:owner.id,eventId:event.id,status:'pending',idempotencyKey:randomUUID(),paymentAccountId:profile.id,stripeAccountId:remote.id,providerMode:'test'});
    await assert.rejects(service.selectEvent(owner.id,event.id,null),{code:'PAYMENT_ACCOUNT_LOCKED'});
    remote.configuration.merchant.capabilities.card_payments.status='restricted';await service.synchronize(owner.id,org.id,profile.id);
    await assert.rejects(resolvePaymentAccount({models:m,event,refresh:false}),{code:'PAYMENTS_NOT_READY'});
    const audit=await m.AuditLog.findAll({where:{organizationId:org.id}});assert.ok(audit.length>=3);assert.equal(JSON.stringify(audit).includes('mock-only'),false);
    const cached=await m.PaymentAccount.findByPk(profile.id);let clock=new Date(+cached.synchronizedAt+1000);
    const slow=deferred(),started=deferred();let retrievals=0;
    const revoked=structuredClone(remote),ready=structuredClone(remote);ready.configuration.merchant.capabilities.card_payments.status='active';
    stripe.retrieveAccount=async()=>{if(++retrievals===1){started.resolve();return slow.promise;}return revoked;};
    const ordered=createBusinessPaymentAccountService({models:m,stripe,now:()=>clock});
    const older=ordered.synchronize(owner.id,org.id,profile.id);await started.promise;
    clock=new Date(+clock+1000);await ordered.synchronizeTrusted(remote.id);
    slow.resolve(ready);await older;await cached.reload();
    assert.equal(cached.chargesEnabled,false);assert.equal(+cached.synchronizedAt,+clock,'freshness remains anchored to newer request observation');
    const closing=deferred(),closingStarted=deferred();retrievals=0;
    stripe.retrieveAccount=async()=>{if(++retrievals===1){closingStarted.resolve();return closing.promise;}return {...ready,closed:true};};
    clock=new Date(+clock+1000);const beforeClose=ordered.synchronize(owner.id,org.id,profile.id);const closedRejection=assert.rejects(beforeClose,{code:'NOT_FOUND'});await closingStarted.promise;
    clock=new Date(+clock+1000);await ordered.synchronizeTrusted(remote.id);
    closing.resolve(ready);await closedRejection;await cached.reload();assert.equal(cached.lifecycleState,'archived');assert.equal(cached.chargesEnabled,false);
  } finally {await db.close();}
});
